name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Copy file example env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create File Database
        run: touch database/database.sqlite

      - name: Run Migration Database
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Node.JS
        run: npm run build

      - name: Notify Telegram on Success
        if: success()
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"chat_id": "CI_CD_NotifierBot", "text": "Laravel CI build succeeded!"}' \
            https://api.telegram.org/6943678766:AAHg5vNMQ8g9Vo5PuAFl04JmVU8Wre41Y_g/sendMessage

      - name: Notify Telegram on Failure
        if: failure()
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"chat_id": "CI_CD_NotifierBot", "text": "Laravel CI build failed!"}' \
            https://api.telegram.org/6943678766:AAHg5vNMQ8g9Vo5PuAFl04JmVU8Wre41Y_g/sendMessage
